services:
  app:
    image: isarfm18/isadorarestaurante:latest
    container_name: isadorarestaurante-app
    ports:
      - "8087:3000"
    environment:
      DB_HOST: mysql-infra 
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
      DB_NAME: isadoradb   
    networks:
      - rede_alunos

networks:
  rede_alunos:
    external: true