name: ci-docker-build

on:
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    name: docker build validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build Docker image
        run: docker build -t isadorarestaurante:${{ github.sha }} .
